### ISSUE TITLE
Add build specification for ingress-nginx-2.15.0

### ISSUE THREAD

**Issue by DenRot** [instana/ingress-nginx-tracing#8]
Hi everybody,

we are currently testing this feature in one of our development environments.
Can you please add a build specification for ingress-nginx-2.15.0?
(Sensor Version 1.1.1 is required as this version is based on nginx version 1.19.2.)

Build Specification:
_[ingress-nginx-2.15.0]
repo=https://github.com/kubernetes/ingress-nginx
tag=ingress-nginx-2.15.0
docker_image=us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.35.0@sha256:fc4979d8b8443a831c9789b5155cded454cb7de737a8b727bc2ba0106d2eae8b
libc_flavor=musl
nginx_version=nginx/1.19.2_

Many thanks in advance.

Best regards,
Dennis

**Comment by sriemer** [comment]
Hi Dennis (@DenRot),

thanks for the report. This repo is rather obsolete now after verification with customers. We have a new strategy to also use our **Instana AutoTrace WebHook** (https://github.com/instana/instana-autotrace-webhook) for this.
We will add support for this `ingress-nginx` version.

Cheers,
Sebastian

**Comment by DenRot** [comment]
Hi Sebastian,

thank you for your answer. A solution with Instana AutoTrace WebHooks is also an option for us, thank you for adding the support of the ingress-nginx version there. I  will therefore close this issue.

Best regards,
Dennis

**Comment by mmanciop** [comment]
Hi @DenRot ,

To avoid miscommunications: we _intend_ to build Ingress NGINX support in the Instana AutoTrace WebHook, but it is very much WIP and it is not something that is likely to happen in the short term.

Best,
  Michele
